name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          submodules: true
      - name: Setup Emscripten toolchain
        uses: mymindstorm/setup-emsdk@v7
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Install
        run: npm i
      - name: Build
        run: npm run build
      - name: Copy to dist
        run: |
          mkdir -p dist
          cp aes-web.c.js dist/
          cp demo.html dist/index.html
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
